### ISSUE TITLE
About Dataset

### ISSUE THREAD

**Issue by innovation64** [OpenMatch/ActiveRAG#1]
I'm a new rag researcher, I wonder how to sample the dataset.
for example, popQA dataset, the source dataset only have this item
'id', 'subj', 'prop', 'obj', 'subj_id', 'prop_id', 'obj_id', 's_aliases', 'o_aliases', 's_uri', 'o_uri', 's_wiki_title', 'o_wiki_title', 's_pop', 'o_pop', 'question', 'possible_answers'
so how to get the passges?
should i download the whole wikipedia content , then use the popqa queries(questions) to retrieve wiki contents? then use the recalling list to rebulid a dataset to do evaluation? like data_popqa_sampled.jsonl?
i will be grateful if you can reply it

**Comment by Pab1x** [comment]
Hi, innovation64

Thanks for your interest in our work!

A1 : For the PopQA dataset, questions and possible answers are enough.

A2 : Yes, if you need to go further to get the passages, you have to download the whole Wikipedia and retrieve them using popqa's queries.

**Comment by innovation64** [comment]
So did ActiveRAG embedding the whole wiki contents about 20G . Then use your retrieval algorithm to select the passages? @Zhipeng-Xu

**Comment by Pab1x** [comment]
Yes, a full retrieval process is required, which is performed by the OpenMatch toolkit using the T5-ACNE model.

**Comment by Pab1x** [comment]
It looks like this issue has been resolved, if you have any other issues, feel free to reopen it.
