### ISSUE TITLE
About the generation of the data_nq_sampled.jsonl file passages field

### ISSUE THREAD

**Issue by BlueCestbon** [OpenMatch/ActiveRAG#2]
data_nq_sampled.jsonl

Seeing that you wrote in your last issue that you used OpenMatch/t5-ance to do the embedding, I went and generated new vector embeddings using generate_passage_embeddings.py in self-rag, the original text is still in the psgsw100.tsv file, and I used the first example in nq { “id”:“-5011119306587397321”, “question”: “who sings the theme song to all that”}, the results of the recall are not quite the same
The text in this file is relatively long, but the array elements in your passages field are relatively short, and there are a lot of data in the format “BULLET::::”.
Is the text column of psgsw100.tsv chunked and processed more carefully when generating the embed?
![image](https://github.com/OpenMatch/ActiveRAG/assets/65054570/0f184b8f-e03a-42cb-81d0-4864815b1e55)

**Comment by Pab1x** [comment]
Hi, @BlueCestbon 
We use the OpenMatch toolkit for retrieval, with all settings consistent with their default settings. Why not try about this one?
Noise ""BULLET::::"" is normal, this is due to the quality of the Wiki-KILT.

**Comment by BlueCestbon** [comment]
> Wiki-KILT

Thanks for your reply. I will try again with OpenMatch toolkit and Wiki-KILT.
